version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend_service
    ports:
      - "3001:3001"
    environment:
      # Inyecta la variable desde el archivo .env
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}

  frontend:
    build: ./frontend
    container_name: frontend_service
    ports:
      # Mapea el puerto de Vite
      - "5173:5173"
    volumes:
      # Sincroniza el código para hot-reloading (cambios en vivo)
      - ./frontend:/app
      # Añade esta línea para evitar problemas con node_modules
      - /app/node_modules
    stdin_open: true
    tty: true